export const data = [
  {
    title: "Nomi",
    tools: "Next · SASS · Adobe XD · Adobe Photoshop",
    overview:
      "Nomi is an interactive web application that allows users to browse and track their favourite movies based on ratings, popularity or release date.",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    designer: "design",
    project: "nomi",
    danial: "Danial",
    reilly: "Reilly",
  },
  {
    title: "Weather App",
    tools: "Next · Tailwind · Adobe XD",
    overview:
      "A Weather Application that utilizes an API Key to fetch short-term forecasts for over 200,000 known cities in the world.",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    designer: "design",
    project: "weather-app",
  },
  {
    title: "Tic Tac Toe",
    tools: "React · CSS",
    overview: "An interactive game built with React and basic CSS styling",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    designer: "design",
    project: "tic-tac-toe",
  },
  {
    title: "Portfolio Project",
    tools: "Next · Tailwind · Figma",
    overview:
      "My portfolio was created with the intention to showcase my work as a developer so far. Utilizing an agile approach, I continuously implemented and revised my designs and some development features. I took it upon myself to study Next.js (and coupled that with Tailwind CSS) to build this site, with the intention that it would allow for future expansion and greater interactivity.",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    designer: "design",
    project: "portfolio",
  },
  {
    title: "Summer Panda Cafe",
    tools: "WordPress · PHP · WooCommerce · Figma",
    overview:
      "A fully customized Website built for a cafe that offers online ordering and other vendor application features. The site was developed using WordPress and WooCommerce plugins in a collaborative team environment",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    designer: "design",
    project: "capstone",
  },
];
