export const data = [
  {
    title: "Nomi",
    tools: "Next, SASS, Adobe XD, Adobe Photoshop",
    overview: "",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    design: "design",
  },
  {
    title: "Weather App",
    tools: "Next, Tailwind",
    overview: "",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    design: "design",
  },
  {
    title: "Tic Tac Toe",
    tools: "React, CSS",
    overview: "",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    design: "design",
  },
  {
    title: "Portfolio",
    tools: "Next, Tailwind, CSS, Figma",
    overview: "",
    github: "",
    liveserver: "",
    timeline: "",
    roles: "",
    design: "",
    development: "",
    takeaway: "",
    dev: "dev",
    design: "design",
  },
];
