export const data = [
  {
    title: "Nomi",
    tools: "Next · SASS · Adobe XD · Adobe Photoshop",
    overview:
      "Nomi is an interactive web application that allows users to browse and track their favourite movies based on ratings, popularity or release date.",
    id: "1",
    image: "/assets/nomi-mockup.png",
    alt: "An interactive Movie Database built with Next.js and Sass",
    github: "https://github.com/JedBorseth/movie-database",
    liveSite: "google.ca",
    timeline: "5 Weeks",
    roles: "UI Designer · Developer · Debugger",
    danial:
      "Thanks for all your help Danial! Wish you all the best in the future!",
    reilly:
      "Reilly! Thanks for helping me out with my designs, you're a rockstar!",
  },
  {
    title: "Weather App",
    tools: "Next · Tailwind · Adobe XD",
    overview:
      "A Weather Application that utilizes an API Key to fetch short-term forecasts for over 200,000 known cities in the world.",
    id: "2",
    image: "/assets/weather-mockup.png",
    alt: "A Weather Application that pulls data from an API and provides realtime forecasts",
    github: "https://github.com/JalenCameron/Weather-Application",
    liveSite: "google.ca",
    timeline: "1 Week",
    roles: "UI Designer · Front-End Developer",
  },
  {
    title: "Tic Tac Toe",
    tools: "React · CSS",
    overview: "An interactive game built with React and basic CSS styling",
    id: "3",
    image: "/assets/game-mockup.png",
    alt: "A fun game of Tic Tac Toe built with React.js and CSS",
    github: "https://github.com/JalenCameron/Tic-Tac-Toe",
    liveSite: "google.ca",
    timeline: "2 Days",
    roles: "UI Designer · Front-End Developer",
  },
  {
    title: "Portfolio Project",
    tools: "Next · Tailwind · Figma",
    overview:
      "My portfolio was created with the intention to showcase my work as a developer so far. Utilizing an agile approach, I continuously implemented and revised my designs and some development features. I took it upon myself to study Next.js (and coupled that with Tailwind CSS) to build this site, with the intention that it would allow for future expansion and greater interactivity.",
    id: "4",
    image: "/assets/portfolio-mockup.png",
    alt: "Jalen Cameron's Portfolio Project",
    github: "https://github.com/JalenCameron/next.js-portfolio",
    liveSite: "google.ca",
    timeline: "2 Weeks",
    roles: "Front-End Developer · UI Designer",
  },
  {
    title: "Summer Panda Cafe",
    tools: "WordPress · PHP · WooCommerce · Figma",
    overview:
      "A fully customized Website built for a cafe that offers online ordering and other vendor application features. The site was developed using WordPress and WooCommerce plugins in a collaborative team environment",
    id: "5",
    image: "/assets/coming-soon.png",
    alt: "A Cafe website built through PHP, WordPress and Sass",
    github: "https://github.com/htpwebdesign/panda-cafe",
    liveSite: "google.ca",
    timeline: "4 Weeks",
    roles: "Front-End Developer · Debugger",
  },
];
